config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("deskbookingsystem42.users.urls", namespace="users")),
    path("booking/", include("deskbookingsystem42.booking.urls", namespace="booking")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

deskbookingsystem42/booking/urls.py
from django.urls import path
from deskbookingsystem42.booking.views import (
    booking_view,
)

app_name = "booking"
urlpatterns = [
    path("", view=booking_view, name="overview"),
]

deskbookingsystem42/users/urls.py
from django.urls import path

from deskbookingsystem42.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

deskbookingsystem42/booking/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.fields import CharField
from django.db.models.fields.related import ForeignKey
from django.utils.translation import gettext_lazy as _

from school.models import School

User = get_user_model()

class Service(models.Model):
    """ 
    Service 
    """
    name    = CharField(_("Name"),max_length=255)
    school  = ForeignKey(School, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = _("Service")
        verbose_name_plural = _("Services")

    def __str__(self):
        return "%s (%s)" % (
            self.name,
            self.school.name,
        )

class Slot(models.Model):
    """ 
    Slot 
    """
    service     = ForeignKey(Service, on_delete=models.CASCADE)
    name        = CharField(_("Name"),max_length=255)
    place_id    = CharField(_("Identification of Place"), max_length=255, blank=True)

    class Meta:
        verbose_name = _("Slot")
        verbose_name_plural = _("Slots")

    def __str__(self):
        return "%s at %s(in %s)" % (
            self.name,
            self.service.name,
            self.service.school.name
        )

class Booking(models.Model):
    """ 
    Booking 
    """
    user    = ForeignKey(User, on_delete=models.CASCADE)
    slot    = ForeignKey(Slot, on_delete=models.CASCADE)
    start   = models.DateTimeField()
    end     = models.DateTimeField()

    class Meta:
        verbose_name = _("Booking")
        verbose_name_plural = _("Bookings")

    def school (self):
        return self.slot.service.school
    
    def service (self):
        return self.slot.service

    def __str__(self):
        return "%s booked %s at %s" % (
            self.user.name,
            self.service,
            self.school,
        )

deskbookingsystem42/school/models.py
from django.db import models
from django.db.models.fields import CharField
from django.utils.translation import gettext_lazy as _

# Create your models here.
class School(models.Model):
    name    = CharField(max_length=255)

    class Meta:
        verbose_name = _("School")
        verbose_name_plural = _("Schools")

    def __str__(self):
        return _("School: %s") % (self.name)

class Key(models.Model):
    """ Key for the Configuration
    TODO: We need to create a fixture with the basic configs...!
    """
    name    = CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = _("Key")
        verbose_name_plural = _("Keys")

    def __str__(self):
        return self.name

class Configuration(models.Model):
    school  = models.ForeignKey(School, related_name="config_list", on_delete=models.CASCADE)
    key     = models.ForeignKey(Key, related_name='config_list', on_delete=models.CASCADE)
    value   = CharField(max_length=255, blank=True)

    class Meta:
        verbose_name = _("Configuration")
        verbose_name_plural = _("Configurations")

    def __str__(self):
        return _("%s: %s => %s") % (self.school.name, self.key.name, self.value)

deskbookingsystem42/users/models.py
from django.contrib.auth import models
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, Model, ForeignKey
from django.db.models.deletion import SET_NULL
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from school.models import School

class Role(Model):
    """Default role for 42users."""
    name = CharField(max_length=200, blank=True)

    class Meta:
        verbose_name = _("Role")
        verbose_name_plural = _("Roles")

    def __str__(self):
        return _("Role: %s" % (self.name))

class User(AbstractUser):
    """Default user for DeskBookingSystem42."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    role = ForeignKey(Role, null=True, blank=True, on_delete=SET_NULL)
    school = ForeignKey(School, null=True, blank=True, on_delete=SET_NULL) 

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

deskbookingsystem42/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

deskbookingsystem42/booking/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from allauth.account.forms import LoginForm, SignupForm

# Create your views here.
class BookingView(TemplateView):
    template_name= "booking/booking-template.html"
    context= {
        'LoginForm': LoginForm(),
        'SignupForm': SignupForm()
    }

    # def add_booking:

    # def remove_booking:
booking_view=BookingView.as_view()

deskbookingsystem42/school/views.py
from django.shortcuts import render

# Create your views here.

deskbookingsystem42/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False, methods=["GET"])
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

deskbookingsystem42/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

deskbookingsystem42/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}DeskBookingSystem42{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Awesome booking with less time requirements">
    <meta name="author" content="42WebCrew">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/vendor.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block css %}
    {% load bootstrap5 %}
    {# @Abdel: Do you have an idea here w/o the cdn? Cheers Phil #}

    <!-- Your stuff: Third-party CSS libraries go here -->{% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">{% endcompress %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Vendor dependencies bundled as one file-->
      {% compress js %}
      <script defer src="{% static 'js/vendor.js' %}"></script>{% endcompress %}
      
      <!-- place project specific Javascript in this file -->{% compress js %}
      <script defer src="{% static 'js/project.js' %}"></script>{% endcompress %}
      
      {% endblock javascript %}
      
      {% load compress %}
      {% compress css %}
      <link type="text/x-scss" href="{% static 'sass/style.scss' %}" rel="stylesheet" media="screen">
      {% endcompress %}
  </head>

  <body>

    
    <div class="container-fluid">
      {% include "header.html"  with LoginForm=LoginForm  SignupForm=SignupForm %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
      {% endfor %}
      {% endif %}

      <div class="d-flex flex-row">
        {% include "navbar.html" %}
        <div class="main-container">
          {% block content %}
             <p>Use this document as a way to quick start any new project.</p>
           {% endblock content %}
        </div>

      </div>


    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>

deskbookingsystem42/templates/header.html
{% load static i18n%}
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">Booking 42</a>

    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        {% if request.user.is_authenticated %}
        <div class="dropdown">
          <button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Logout</a>
          </div>
        </div>
        {% else %}
        <button type="button" class="btn" data-toggle="modal" data-target="#signinModel">
          <i class="fas fa-user"></i>
        </button>
        {% include "signup-modals.html" with LoginForm=LoginForm  SignupForm=SignupForm%}
        {% endif %}
      </li>
    </ul>
  </nav>

deskbookingsystem42/templates/navbar.html
{% load static i18n%}

<div class="side-navbar  bg-light navbar d-flex flex-column">
    <ul class="navbar-nav">
        <li class="nav-item text-center mb-4" >
           <a  class="btn"href="{% url 'home' %}">
               <i class="fas fa-tachometer-alt"></i>
                <span>Dashboard</span>
           </a> 
        </li>
        <li class="nav-item text-center mb-4">
           <a  class="btn" href="{% url 'home' %}">
               <i class="far fa-calendar-alt"></i>
               <span>Calendar</span>
           </a>
        </li>
        <li class="nav-item text-center mb-4">
            <a  class="btn" href="{% url 'booking:overview' %}">
                <i class="far fa-edit"></i>
                <span>Booking</span>

            </a>
            <li class="nav-item text-center">
                <a  class="btn" href="{% url 'booking:overview' %}">
                    <i class="fas fa-cog"></i>
                    <span>Booking</span>
    
                </a>
        </li>

    </ul>
</div>

deskbookingsystem42/templates/signup-modals.html
{% load crispy_forms_tags %}
{% load i18n %}
{% load account socialaccount %}
<div class="modal show in" id="signinModel" tabindex="-1" role="dialog" aria-labelledby="signinModelLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signinModelLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="login-form">
                    <form class="login" method="POST" action="{% url 'account_login' %}">
                      {% csrf_token %}
                      {{ LoginForm|crispy }}
                      {% if redirect_field_value %}
                      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                      {% endif %}
                      <button class="btn btn-primary btn-block btn-medium mb-3" type="submit">{% trans "Login" %}</button>
                      <a class="btn btn-primary btn-block btn-medium" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
                    </form>
                  </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>


<div class="modal show in" id="signinModel" tabindex="-1" role="dialog" aria-labelledby="signinModelLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signinModelLabel">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="signup-form">
                    <form class="signup" id="signup_form" method="post" action="{% url 'account_signup' %}">
                      {% csrf_token %}
                      {{ SignupForm|crispy }}
                      {% if redirect_field_value %}
                      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                      {% endif %}
                      <button class='btn btn-primary btn-block btn-medium mb-3' type="submit">{% trans "CREATE NEW ACCOUNT" %}</button>
                    </form>
                  </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>